# Generated by Django 5.0.6 on 2024-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='extra_products',
            field=models.ManyToManyField(default=None, to='pizza.productextra'),
        ),
    ]
