# Generated by Django 5.0.6 on 2024-06-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_productsize_extra_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='extra_products',
        ),
    ]
