# Generated by Django 5.0.4 on 2024-06-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_remove_productsize_extra_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.region')),
            ],
        ),
    ]
