# Generated by Django 5.0.4 on 2024-06-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_remove_productsize_product_productsize_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='extra_products',
            field=models.ManyToManyField(default=None, null=True, to='pizza.productextra'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.product'),
        ),
    ]
