# Generated by Django 5.0.4 on 2024-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_remove_productsize_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(default=None, null=True, to='pizza.productsize'),
        ),
    ]
