# Generated by Django 5.0.4 on 2024-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='pizza.productsize'),
        ),
    ]
